team/urls.py
from django.urls import path
from .views import ClubView, PlayerView

urlpatterns = [
    path('club/<pk>/', ClubView.as_view(), name='club-detail'),
    path('player/<pk>/', PlayerView.as_view(), name='player-detail')
]

valutac_league/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('', include('team.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event/models.py
from django.db import models


class Match(models.Model):

    date = models.DateField()
    first_team = models.ForeignKey('team.Club', on_delete=models.CASCADE, related_name='Matchs_first_team')
    second_team = models.ForeignKey('team.Club', on_delete=models.CASCADE, related_name='Matchs_second_team')
    # total_goals = models.IntegerField()

    def __str__(self):
        return "{} - {}".format(self.first_team, self.second_team)

    def get_first_team_goals(self):
        goal_event = self.match_details.filter(type='goal', player__club=self.first_team).count()
        return goal_event

    def get_second_team_goals(self):
        goal_event = self.match_details.filter(type='goal', player__club=self.second_team).count()
        return goal_event

    def get_winner_team(self):

        if self.get_first_team_goals() > self.get_second_team_goals():
            return self.first_team

        if self.get_second_team_goals() > self.get_first_team_goals():
            return self.second_team

        if self.get_first_team_goals() == self.get_second_team_goals():
            return None


class MatchDetail(models.Model):

    EVENT_TYPE = (
        ('goal', 'GOAL'),
        ('own_goal', 'OWN GOAL'),
        ('assist', 'ASSIT'),
        ('red_card', 'RED CARD'),
        ('yellow_card', 'YELLOW CARD'),
        ('penalty_success', 'PENALTY SUCCESS'),
        ('penalty_failed', 'PENALTY FAILED'),
    )

    match = models.ForeignKey('event.Match', on_delete=models.CASCADE, related_name='match_details')
    type = models.CharField(max_length=50, choices=EVENT_TYPE)
    player = models.ForeignKey('team.Player', on_delete=models.CASCADE)
    time = models.CharField(max_length=10)

team/models.py
import locale
from django.db import models
from django.db.models import Q
from event.models import Match, MatchDetail


class Club(models.Model):
    NATIOLITY_TYPE = (
        ('id', 'INDONESIA'),
    )

    name = models.CharField(max_length=50)
    founded_year = models.IntegerField()
    natiolity = models.CharField(max_length=5, choices=NATIOLITY_TYPE)
    description = models.CharField(max_length=255)
    logo = models.ImageField(upload_to="uploads/")

    def __str__(self):
        return self.name

    def get_win_amount(self):
        amount = 0
        for match in Match.objects.filter(Q(first_team_id=self.id)|Q(second_team_id=self.id)):
            if match.get_winner_team() is not None and match.get_winner_team().id == self.id:
                amount+=1
        return amount

    def get_draw_amount(self):
        amount = 0
        for match in Match.objects.filter(Q(first_team_id=self.id)|Q(second_team_id=self.id)):
            if match.get_winner_team() is None:
                amount += 1
        return amount

    def get_loose_amount(self):
        amount = 0
        for match in Match.objects.filter(Q(first_team_id=self.id)|Q(second_team_id=self.id)):
            if match.get_winner_team() is not None and match.get_winner_team().id != self.id:
                amount+=1
        return amount

    def get_goal_for(self):
        goals_for = [match for match in MatchDetail.objects.filter(player__club_id=self.id)]
        return len(goals_for)

    def get_goal_against(self):
        amount = 0

        for match in self.Matchs_first_team.all():
            amount += match.get_second_team_goals()

        for match in self.Matchs_second_team.all():
            amount += match.get_first_team_goals()

        return amount

    def get_goal_differents(self):
        return self.get_goal_for() - self.get_goal_against()

    def get_points(self):
        points = 0
        points += self.get_win_amount() * 3
        points += self.get_draw_amount() * 1
        return points

    def get_matches(self):
        matches = Match.objects.filter(Q(first_team_id=self.id) | Q(second_team_id=self.id))
        return matches


class Player(models.Model):
    PREFERRED_FOOT_TYPE = (
        ('l', 'LEFT'),
        ('r', 'RIGHT'),
        ('b', 'BOTH')
    )

    NATIOLITY_TYPE = (
        ('id', 'INDONESIA'),
    )

    INJURY_TYPE = (
        ('a', 'A'),
        ('b', 'B'),
        ('c', 'C'),
        ('d', 'D'),
    )

    POSITION_CODE_TYPE = (
        ('cf', 'CF'),
        ('mf', 'MF'),
        ('cb', 'CB')
    )

    club = models.ForeignKey(Club, related_name='players', on_delete=models.CASCADE)

    image = models.ImageField(upload_to="uploads/")
    name = models.CharField(max_length=100)
    player_number = models.IntegerField()
    preferred_foot = models.CharField(max_length=1, choices=PREFERRED_FOOT_TYPE)
    natiolity = models.CharField(max_length=3, choices=NATIOLITY_TYPE)
    injury = models.CharField(max_length=1, choices=INJURY_TYPE)
    position_name = models.CharField(max_length=50)
    position_code = models.CharField(max_length=5, choices=POSITION_CODE_TYPE)

    balance = models.IntegerField()
    stamina = models.IntegerField()
    passing = models.IntegerField()
    shooting = models.IntegerField()
    skill = models.IntegerField()
    attack = models.IntegerField()
    dribbling = models.IntegerField()
    ability = models.IntegerField()
    defend = models.IntegerField()

    def __str__(self):
        return self.name

    def get_goals(self):
        amount = MatchDetail.objects.filter(player_id=self.id, type='goal').count()
        return amount

    def get_own_goals(self):
        amount = MatchDetail.objects.filter(player_id=self.id, type='own_goal').count()
        return amount

    def get_assists(self):
        amount = MatchDetail.objects.filter(player_id=self.id, type='assist').count()
        return amount

    def get_red_cards(self):
        amount = MatchDetail.objects.filter(player_id=self.id, type='red_card').count()
        return amount

    def get_yellow_cards(self):
        amount = MatchDetail.objects.filter(player_id=self.id, type='yellow_card').count()
        return amount

    def get_penalty_success(self):
        amount = MatchDetail.objects.filter(player_id=self.id, type='penalty_success').count()
        return amount

    def get_penalty_failed(self):
        amount = MatchDetail.objects.filter(player_id=self.id, type='penalty_failed').count()
        return amount

    def get_overall_amount(self):
        amount = [self.balance, self.stamina, self.passing, self.shooting, self.skill, self.attack, self.dribbling, self.ability, self.defend]
        return locale.format('%.2f', sum(amount)/len(amount))

event/views.py
from django.shortcuts import render

# Create your views here.

team/views.py
import datetime
from django.views.generic import DetailView
from django.db.models import Q
from .models import Club, Player
from team.models import Match
from django.db.models.functions import TruncMonth, TruncDate

class ClubView(DetailView):
    model = Club
    template_name = 'club.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['matches'] = []

        club = self.get_object()
        dates = []
        for match in club.get_matches():
            match_date = match.date.strftime("%d/%m/%Y")

            if match_date not in dates:
                dates.append(match_date)

        for date in dates:
            date = datetime.datetime.strptime(date, "%d/%m/%Y").date()
            context['matches'].append({"date":date, 'matches':club.get_matches().filter(date=date)})

        return context


class PlayerView(DetailView):
    model = Player
    template_name = 'player.html'

valutac_league/views.py
from django.views.generic import TemplateView
from team.models import Club, Player
from operator import itemgetter


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['teams'] = Club.objects.all()
        context['players'] = Player.objects.all()


        player_goals = [{'player':player, 'goals':player.get_goals()} for player in Player.objects.all()]
        context['player_goals']= sorted(player_goals, key=itemgetter('goals'), reverse=True)

        return context

team/templates/club.html
{% extends "base.html" %}
{% block title %}
{{ club.name }}
{%endblock%}

{% block content %}
<div class="container" id="content">
            <div class="row">
                <div class="col-md-12">
                <h2>{{ club.name }}</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <img src="{{ club.logo.url }}" alt="" class="img-responsive img-thumbnail" width="140px">
                </div>
                <div class="col-md-10">
                    <dl>
                        <dt>Club Name</dt>
                        <dd>{{club.name}}</dd>
                        <dt>Year Founded</dt>
                        <dd>{{ club.founded_year }}</dd>
                        <dt>Country</dt>
                        <dd>{{club.get_natiolity_display}}</dd>
                    </dl>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="">
                        <h4>Player Stats</h4>
                    </div>
                    <table class="table table-hover table-striped">
                        <tr style="background:#011b51;color:#fff">
                            <th width="10px">Pos</th>
                            <th>No</th>
                            <th>Player Name</th>
                            <th>M</th>
                            <th>G</th>
                            <th>A</th>
                            <th>OG</th>
                            <th><span class="icon-yellow glyphicon glyphicon-stop"></span></th>
                            <th><span class="icon-red glyphicon glyphicon-stop"></span></th>
                        </tr>

                        {% for player in club.players.all %}
                        <tr >
                            <td>
                                {% if player.position_code == 'cf' %}
                                <span class="label label-danger">
                                {% elif player.position_code == 'mf' %}
                                <span class="label label-success">
                                {% elif player.position_code == 'cb' %}
                                <span class="label label-info">
                                {% endif %}
                                    {{ player.get_position_code_display }}
                                </span>
                            </td>
                            <td>{{ player.player_number }}</td>
                            <td>{{ player.name }}</td>
                            <td>{{ player.club.Matchs_first_team.count |add:player.club.Matchs_first_team.count }}</td>
                            <td>{{ player.get_goals }}</td>
                            <td>{{ player.get_assists}}</td>
                            <td>{{ player.get_own_goals }}</td>
                            <td>{{ player.get_yellow_cards }}</td>
                            <td>{{ player.get_red_cards }}</td>
                        </tr>
                        {% endfor %}
                    </table>
                    <div class="alert alert-info" role="alert"><strong>M</strong>: MATCH <br><strong>G</strong>: GOALS <br><strong>A</strong>: ASSISTS <br><strong>OG</strong>: OWN GOALS</div>
                </div>
            </div>
            <div class="row">
                    <div class="col-md-12">
                        <div class="">
                          <h4>Fixtures</h4>
                        </div>
                        {% for match_date in matches %}
                        <table class="table table-hover table-striped">
                            <tr style="background:#011b51;color:#fff">
                                <th style="text-align:right"></th>
                                <th style="text-align:center">{{ match_date.date | date:"d/m/Y"}}</th>
                                <th style="text-align:left"></th>
                            </tr>
                            {% for  match in match_date.matches %}
                            <tr>
                                <td style="text-align:right">{{match.first_team.name}} <img src="{{match.first_team.logo.url}}" width="24px"></td>
                                <td style="text-align:center"><strong>{{ match.get_first_team_goals }}</strong> vs <strong>{{ match.get_second_team_goals }}</strong></td>
                                <td style="text-align:left"><img src="{{ match.second_team.logo.url }}" width="24px"> {{match.second_team.name}}</td>
                            </tr>
                            {% endfor %}
                        </table>
                        {% endfor %}
                        </div>
                </div>
        </div>
{% endblock %}

team/templates/player.html
{% extends "base.html" %}
{% block title %}
{{ player.name }}
{%endblock%}

{% block content %}
    <div class="container">
      <div class="row" style="margin-top: 8%;">
        <div class="col-md-4 col-sm-4 text-center">
          <img class="img-responsive img-thumbnail" src="{{ player.image.url }}" style="width:180px;">
        </div>
        <div class="col-md-8 col-sm-8">
          <div class="row">
            <div class="col-md-6 col-sm-6">
              <h2>{{ player.name }} <span class="label label-danger">94</span></h2>
              <h3>{{ player.position_name }}</h3>
              <h3>
                  {% if player.position_code == 'cf' %}
                  <span class="label label-danger">
                  {% elif player.position_code == 'mf' %}
                  <span class="label label-success">
                  {% elif player.position_code == 'cb' %}
                  <span class="label label-info">
                  {% endif %}
                  {{player.get_position_code_display}}
                  </span>
              </h3>
            </div>
            <div class="col-md-4 col-sm-4 text-right">
              <h2>{{ player.club.name }}</h2>
              <img src="{{ player.club.logo.url}}" width="48px">
            </div>
          </div>
        </div>
      </div>
      <div class="row" style="padding-top: 24px;">
        <div class="col-md-4">
          <table class="table">
            <tr>
              <td>OVERALL</td>
              <td><span class="label label-danger">{{player.get_overall_amount}}</span></td>
            </tr>
            <tr>
              <td>VALUE</td>
              <td>USD $</td>
            </tr>
            <tr>
              <td>PREFERRED FOOT</td>
              <td>{{ player.get_preferred_foot_display }}</td>
            </tr>
            <tr>
              <td>NATIONALITY</td>
              <td>{{ player.get_natiolity_display}}</td>
            </tr>
            <tr>
              <td>INJURY</td>
              <td><span class="label label-warning">{{player.get_injury_display}}</span></td>
            </tr>
          </table>
        </div>
        <div class="col-md-8">
          <table class="table">
            <tr>
              <td>BALANCE</td>
              <td>
                  {% if player.balance >= 90 %}
                  <span class="label label-danger">
                  {% elif player.balance >= 80 and player.balance < 90%}
                  <span class="label label-success">
                  {% elif player.balance < 80 and player.balance >= 70 %}
                  <span class="label label-info">
                  {% elif player.balance < 70 %}
                  <span class="label label-danger">
                  {% endif %}
                      {{player.balance}}
                  </span>
              </td>

                <td>DRIBBLING</td>
              <td>
                  {% if player.dribbling >= 90 %}
                  <span class="label label-danger">
                  {% elif player.dribbling >= 80 and player.dribbling < 90 %}
                  <span class="label label-success">
                  {% elif player.dribbling < 80 and player.dribling >= 70 %}
                  <span class="label label-info">
                  {% elif player.dribling < 70 %}
                  <span class="label label-danger">
                  {% endif %}
                      {{player.dribbling}}
                  </span>
              </td>
            </tr>
            <tr>
              <td>STAMINA</td>
              <td>
                  {% if player.stamina >= 90 %}
                  <span class="label label-danger">
                  {% elif player.stamina >= 80 and player.stamina < 90 %}
                  <span class="label label-success">
                  {% elif player.stamina < 80 and player.stamina >= 70 %}
                  <span class="label label-info">
                  {% elif player.stamina < 70 %}
                  <span class="label label-danger">
                  {% endif %}
                      {{player.stamina}}
                  </span>
              </td>
              <td>SHOOTING</td>
              <td>
                  {% if player.shooting >= 90 %}
                  <span class="label label-danger">
                  {% elif player.shooting >= 80 and player.shooting < 90 %}
                  <span class="label label-success">
                  {% elif player.shooting < 80 and player.shooting >= 70 %}
                  <span class="label label-info">
                  {% elif player.shooting < 70 %}
                  <span class="label label-danger">
                  {% endif %}
                      {{player.shooting}}
                  </span>
              </td>
            </tr>
            <tr>
              <td>PASSING</td>
              <td>
                  {% if player.passing >= 90 %}
                  <span class="label label-danger">
                  {% elif player.passing >= 80 and player.passing < 90 %}
                  <span class="label label-success">
                  {% elif player.passing < 80 and player.passing >= 70 %}
                  <span class="label label-info">
                  {% elif player.passing < 70 %}
                  <span class="label label-danger">
                  {% endif %}
                      {{player.passing}}
                  </span>
              </td>
              <td>ABILITY</td>
              <td>
                  {% if player.ability >= 90 %}
                  <span class="label label-danger">
                  {% elif player.ability >= 80 and player.ability < 90 %}
                  <span class="label label-success">
                  {% elif player.ability < 80 and player.ability >= 70 %}
                  <span class="label label-info">
                  {% elif player.ability < 70 %}
                  <span class="label label-danger">
                  {% endif %}
                      {{player.ability}}
                  </span>
              </td>
            </tr>
            <tr>
              <td>SKILL</td>
              <td>
                  {% if player.skill >= 90 %}
                  <span class="label label-danger">
                  {% elif player.skill >= 80 and player.skill < 90 %}
                  <span class="label label-success">
                  {% elif player.skill < 80 and player.skill >= 70 %}
                  <span class="label label-info">
                  {% elif player.skill < 70 %}
                  <span class="label label-danger">
                  {% endif %}
                      {{player.skill}}
                  </span>
              </td>
              <td>DEFEND</td>
              <td>
                  {% if player.defend >= 90 %}
                  <span class="label label-danger">
                  {% elif player.defend >= 80 and player.defend < 90 %}
                  <span class="label label-success">
                  {% elif player.defend < 80 and player.defend >= 70 %}
                  <span class="label label-info">
                  {% elif player.defend < 70 %}
                  <span class="label label-danger">
                  {% endif %}
                      {{player.defend}}
                  </span>
              </td>
            </tr>
            <tr>
              <td>ATTACK</td>
              <td>
                  {% if player.attack >= 90 %}
                  <span class="label label-danger">
                  {% elif player.attack >= 80 and player.attack < 90 %}
                  <span class="label label-success">
                  {% elif player.attack < 80 and player.attack >= 70 %}
                  <span class="label label-info">
                  {% elif player.attack < 70 %}
                  <span class="label label-danger">
                  {% endif %}
                      {{player.attack}}
                  </span>
              </td>
              <td></td>
              <td></td>
            </tr>
          </table>
        </div>
      </div>
      <div class="row">
          <div class="col-md-12">
              <div class="">
                  <h4>Careers</h4>
              </div>
              <div class="table-responsive">
              <table class="table table-hover table-striped">
                  <tr style="background:#011b51;color:#fff">
                      <th>Team</th>
                      <th>Season</th>
                      <th width="10%">Pos</th>
                      <th width="8%">M</th>
                      <th width="8%">G</th>
                      <th width="8%">A</th>
                      <th width="8%">OG</th>
                      <th width="8%"><span class="icon-yellow glyphicon glyphicon-stop"></span></th>
                      <th width="8%"><span class="icon-red glyphicon glyphicon-stop"></span></th>
                  </tr>
                  <tr >
                      <td>Doa Ibu</td>
                      <td>March 2018</td>
                      <td><span class="label label-success">MF</span></td>
                      <td>2</td>
                      <td>11</td>
                      <td>12</td>
                      <td>2</td>
                      <td>0</td>
                      <td>0</td>
                  </tr>
              </table>
            </div>
          </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="">
                    <h4>History</h4>
                </div>
                <div class="table-responsive">
                <table class="table table-hover table-striped">
                    <tr style="background:#011b51;color:#fff">
                        <th width="15%">Team</th>
                        <th width="15%">Oppo</th>
                        <th width="15%">Date</th>
                        <th width="15%">Score</th>
                        <th width="8%">G</th>
                        <th width="8%">A</th>
                        <th width="8%">OG</th>
                        <th width="8%"><span class="icon-yellow glyphicon glyphicon-stop"></span></th>
                        <th width="8%"><span class="icon-red glyphicon glyphicon-stop"></span></th>
                    </tr>
                    <tr >
                        <td>Doa Ibu</td>
                        <td>White Walker</td>
                        <td>10/03/2018</td>
                        <td>W 8 - 3</td>
                        <td>3</td>
                        <td>5</td>
                        <td>1</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                        <td>Doa Ibu</td>
                        <td>Nightfurry</td>
                        <td>10/03/2018</td>
                        <td>W 15 - 10</td>
                        <td>8</td>
                        <td>7</td>
                        <td>1</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                </table>
              </div>
            </div>
          </div>
    </div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %} {% endblock%}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/sticky_footer_bootstrap.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700" rel="stylesheet">
</head>
<body>

    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Valutac League</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="https://valutac.com/company/team/">About us</a></li>
                    <!-- <li><a href="#contact">Contact</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li role="separator" class="divider"></li>
                                <li class="dropdown-header">Nav header</li>
                                <li><a href="#">Separated link</a></li>
                                <li><a href="#">One more separated link</a></li>
                            </ul>
                        </li> -->
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        {% block content %}

        {% endblock %}
        <footer class="footer">
            <div class="container">
                <p class="text-muted">&copy Valutac. All rights reserved except where noted</p>
            </div>
        </footer>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.js' %}">
        </body>
</html>